// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edzxunyjqfxardamvkcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkenh1bnlqcWZ4YXJkYW12a2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNzYyODIsImV4cCI6MjA1Mjc1MjI4Mn0.Z_Ab-jDzpqEE5OXC9yj9HkQHG7wRel528Gh9r5i7x-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);